#!/usr/bin/env python3
"""entry_owners.py - the decided owner of every entry point, the aliases, and the twin parity matrix.

Review items 1, 6, 7, 22, 26 (2026-09-10). The deploy decides where each file lives (its manifest and
its dest() rule); the checkout holds twins (bin/x.py, bin/x_y.py, scripts/x.py) and symlink aliases.
Nothing here guesses: it reads the deploy's own lists, the repository's own links, and compares twins
byte for byte. The output is the table the review asked for, generated so it cannot go stale.

    python3 entry_owners.py            print the tables
    python3 entry_owners.py --write    also write docs/entry-owners.md

Owner rules (from scripts/deploy-atelier.sh):
  SCRIPTS      -> ~/.vintos/workspace/scripts/<name> (his organs; cron runs them from there)
  BINS         -> the existing copy found by locate(): beside the anchor (workspace/scripts) if one is
                  there, else the tree holding most of the manifest, else the anchor; the server unit
                  runs bin/server.py from where the unit file says
  EXECUTABLE   -> chmod 755 after install (cron or systemd runs the file directly)
  SKILLFILES   -> installed at the same relative path under the workspace
"""
import os, re, sys, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEPLOY = os.path.join(HERE, "deploy-atelier.sh")


def _lists():
    txt = open(DEPLOY).read()
    out = {"SCRIPTS": [], "BINS": [], "EXECUTABLE": [], "SKILLFILES": []}
    for var in out:
        for m in re.finditer(r'^%s="(.*?)"' % var, txt, re.M | re.S):
            body = m.group(1).replace("$%s" % var, " ")
            out[var] += [t for t in body.split() if not t.startswith("#") and t not in ("", "\\")]
    for var in out:
        seen = []; [seen.append(x) for x in out[var] if x not in seen]; out[var] = seen
    return out


def _sha(p):
    try:
        return hashlib.sha256(open(p, "rb").read()).hexdigest()[:12]
    except Exception:
        return None


def aliases():
    """Symlinks in scripts/ and bin/: name -> target, resolved or dangling."""
    rows = []
    for d in ("scripts", "bin"):
        dd = os.path.join(REPO, d)
        for f in sorted(os.listdir(dd)) if os.path.isdir(dd) else []:
            p = os.path.join(dd, f)
            if os.path.islink(p):
                tgt = os.readlink(p)
                rows.append({"alias": "%s/%s" % (d, f), "target": tgt, "resolves_in_checkout": os.path.exists(p),
                             "note": "host path: resolves on Aegis only" if tgt.startswith("/home/") else ""})
    return rows


def _variants(name):
    stem, ext = os.path.splitext(name)
    return {stem.replace("-", "_") + ext, stem.replace("_", "-") + ext, name}


def parity():
    """Every twin set (same stem, dash/underscore, bin/scripts): identical or not, which is deployed."""
    L = _lists(); files = {}
    for d in ("bin", "scripts"):
        dd = os.path.join(REPO, d)
        for f in os.listdir(dd) if os.path.isdir(dd) else []:
            p = os.path.join(dd, f)
            if os.path.isfile(p) and not os.path.islink(p) and f.endswith((".py", ".sh")):
                files.setdefault(f, []).append(d)
    seen = set(); rows = []
    for f in sorted(files):
        key = re.sub(r"[-_]", "", os.path.splitext(f)[0]) + os.path.splitext(f)[1]
        if key in seen: continue
        seen.add(key)
        members = sorted({"%s/%s" % (d, g) for g in files if re.sub(r"[-_]", "", os.path.splitext(g)[0]) + os.path.splitext(g)[1] == key for d in files[g]})
        if len(members) < 2: continue
        shas = {m: _sha(os.path.join(REPO, m)) for m in members}
        deployed = [m for m in members if os.path.basename(m) in L["SCRIPTS"] + L["BINS"]]
        rows.append({"twins": members, "identical": len(set(shas.values())) == 1, "sha": shas,
                     "deployed": deployed or ["(not in the manifest)"]})
    return rows


def owners():
    L = _lists(); rows = []
    for f in L["SCRIPTS"]:
        rows.append({"entry": f, "owner": "~/.vintos/workspace/scripts/%s" % f, "rule": "SCRIPTS", "executable": f in L["EXECUTABLE"], "in_checkout": os.path.exists(os.path.join(REPO, "scripts", f))})
    for f in L["BINS"]:
        rows.append({"entry": f, "owner": "the located twin (deploy dest(): beside the anchor, else the tree holding most kin, else workspace/scripts)", "rule": "BINS", "executable": f in L["EXECUTABLE"], "in_checkout": os.path.exists(os.path.join(REPO, "bin", f))})
    for f in L["SKILLFILES"]:
        rows.append({"entry": f, "owner": "~/.vintos/workspace/%s" % f, "rule": "SKILLFILES", "executable": True, "in_checkout": os.path.exists(os.path.join(REPO, f))})
    return rows


def render():
    o, a, p = owners(), aliases(), parity()
    out = ["# Entry points: decided owners, aliases, twin parity", "",
           "Generated by `scripts/entry_owners.py` from the deploy manifest and the checkout (review items 1, 6, 7, 22, 26). Regenerate with `python3 scripts/entry_owners.py --write`.", "",
           "## Owners (%d entries)" % len(o), "", "| entry | rule | installed at | executable | in checkout |", "|---|---|---|---|---|"]
    out += ["| %s | %s | %s | %s | %s |" % (r["entry"], r["rule"], r["owner"], "yes" if r["executable"] else "", "yes" if r["in_checkout"] else "MISSING") for r in o]
    out += ["", "## Aliases (%d symlinks kept on purpose)" % len(a), "", "| alias | target | resolves here | note |", "|---|---|---|---|"]
    out += ["| %s | %s | %s | %s |" % (r["alias"], r["target"], "yes" if r["resolves_in_checkout"] else "no", r["note"]) for r in a]
    out += ["", "## Twin parity (%d sets)" % len(p), "", "| twins | identical | deployed member |", "|---|---|---|"]
    out += ["| %s | %s | %s |" % (", ".join(r["twins"]), "yes" if r["identical"] else "NO: " + ", ".join("%s=%s" % (k, v) for k, v in r["sha"].items()), ", ".join(r["deployed"])) for r in p]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    if "--write" in sys.argv:
        open(os.path.join(REPO, "docs", "entry-owners.md"), "w").write(text); print("written docs/entry-owners.md")
    else:
        print(text)
