#!/usr/bin/env python3
"""untested_report.py - the runtime paths no test touches, reported instead of assumed.

Review item 388 (2026-09-10). Reads the server's routes (AST) and every script/bin module, then every
file under broker/tests, and reports which routes and which modules no test names. A path in this
report is not known to work; it is known to be unexercised.

    python3 untested_report.py            print the report
    python3 untested_report.py --write    also write docs/untested.md
"""
import os, re, sys, ast
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(HERE)


def routes():
    out = []
    def walk(node):
        for ch in ast.iter_child_nodes(node):
            if isinstance(ch, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for d in ch.decorator_list:
                    if isinstance(d, ast.Call) and isinstance(d.func, ast.Attribute) and d.func.attr in ("get", "post", "put", "delete", "patch", "websocket") and d.args and isinstance(d.args[0], ast.Constant):
                        out.append((d.func.attr.upper(), d.args[0].value, ch.name))
            walk(ch)
    sources = [Path(REPO) / "bin/server.py"] + sorted((Path(REPO) / "bin/server_domains").glob("*.py"))
    for source in sources:
        walk(ast.parse(source.read_text(errors="replace")))
    return out


def modules():
    out = []
    for d in ("scripts", "bin"):
        for f in sorted(os.listdir(os.path.join(REPO, d))):
            p = os.path.join(REPO, d, f)
            if f.endswith((".py", ".sh")) and os.path.isfile(p) and not os.path.islink(p):
                out.append(f)
    out += ["server_domains/" + p.name for p in (Path(REPO) / "bin/server_domains").glob("*.py") if not p.is_symlink()]
    return sorted(set(out))


def tests_text():
    t = ""
    td = os.path.join(REPO, "broker", "tests")
    for f in os.listdir(td):
        if f.startswith("test_") and f.endswith(".py"):
            t += open(os.path.join(td, f), errors="replace").read() + "\n"
    return t


def report():
    tt = tests_text()
    rs = routes(); ms = modules()
    untested_routes = [r for r in rs if r[1] not in tt and r[2] not in tt]
    untested_modules = [m for m in ms if m not in tt and os.path.splitext(m)[0] not in tt and os.path.splitext(m)[0].replace("-", "_") not in tt]
    return {"routes_total": len(rs), "routes_untested": untested_routes, "modules_total": len(ms), "modules_untested": untested_modules}


def render():
    r = report()
    out = ["# Untested runtime paths", "",
           "Generated by `scripts/untested_report.py` (review item 388): what no file under `broker/tests` names. Unexercised, not known-good. Regenerate with `python3 scripts/untested_report.py --write`.", "",
           "## Routes: %d of %d untested" % (len(r["routes_untested"]), r["routes_total"]), ""]
    out += ["- `%s %s` (%s)" % x for x in r["routes_untested"]]
    out += ["", "## Modules: %d of %d untested" % (len(r["modules_untested"]), r["modules_total"]), ""]
    out += ["- `%s`" % m for m in r["modules_untested"]]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    t = render()
    if "--write" in sys.argv:
        open(os.path.join(REPO, "docs", "untested.md"), "w").write(t); print("written docs/untested.md")
    else:
        print(t)
